name: Deploy Storybook

on: deployment_status

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy Storybook
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static

      - name: Run Storybook tests
        run: npm run test-storybook

        env: 
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
          TARGET_URL: '${{ github.event.deployment_status.target_url }}'
