name: Storybook Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run Storybook tests
        run: npm run test-storybook:ci
